qa:
  users:
    valid_user: "standard_user"
    invalid_user: "invalid_user"
    locked_user: "locked_out_user"
  reports_path: "target/reports"

preprod:
  users:
    valid_user: "standard_user"
    invalid_user: "invalid_user"
    locked_user: "locked_out_user"
  reports_path: "target/reports"
