# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Requests API testing

env:
  REQUIREMENTS_FILENAME: requirements.txt

on:
  push:
    branches: [ "main" ]
    paths:
      - python-request-api/**
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        cd python-request-api
        python -m pip install --upgrade pip
        if [ -f ${{env.REQUIREMENTS_FILENAME}} ]; then pip install -r ${{env.REQUIREMENTS_FILENAME}}; fi
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Add json-server dependency
      run: |
        npm install -g json-server
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        cd python-request-api
        sh tests_runner.sh
