name: RestAssured GraphQL API testing - JUnit5

env:
  PROJECT_NAME: restassured_junit5_graphql_api_simple

on:
  push:
    branches: [ "main" ]
    paths:
      - restassured_junit5_graphql_api_simple/**
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2

      - name: Run Tests
        run: |
          cd ${{env.PROJECT_NAME}}
          mvn clean test
